theaters:
  nttr:
    name: Nellis Test & Training Range
    channels:
      - name: Flight/Squadron specific
      - name: Nellis Clearance Delivery
        freq: 289.4
      - name: Nellis Ground
        freq: 275.8
      - name: Nellis Tower
        freq: 327.0
      - name: Nellis Approach/Departure West
        freq: 385.4
      - name: Nellis Approach/Departure East
        freq: 273.55
      - name: Nellis Control -- Sally
        freq: 317.525
      - name: Nellis Control-- Lee
        freq: 254.4
      - name: SOF Bullseye
        freq: 305.6
      - name: EMERGENCY SINGLE FRQ
        freq: 343.725
      - name: Nellis ATIS
        freq: 270.1
      - name: Creech AFB Tower
        freq: 360.625
      - name: HAVE QUICK 13
        freq: 250.1
      - name: HAVE QUICK 14
        freq: 251.1
      - name: HAVE QUICK 15
        freq: 252.1
      - name: Blackjack
        freq: 377.8
      - name: KC-135 AR-641A
        freq: 265.0
      - name: KC-135MPRS AR-635
        freq: 360.8
      - name: KC-135MPRS AR-625
        freq: 319.8
      - name: HAVE QUICK 20
        freq: 300.05
    airbases:
      nellis:
        name: Nellis AFB
        tacan: 12X
        atis: 270.1
        clearance: 289.4
        ground: 275.8
        tower: 327.0
        approach: 291.725
        departure: 385.4
        takeoff: 3R
        land: 21L
        runways:
          - name: 3R
            length: 10051
            elevation: 1841
          - name: 21L
            length: 10051
            elevation: 1854
            ils: 109.1
          - name: 3L
            length: 10120
            elevation: 1841
          - name: 21R
            length: 10120
            elevation: 1857
        departures:
          fyttr3: FYTTR THREE
          fyttr_low: FYTTR LOW
          tac_north: A10 TAC NORTH
          tac_west: A10 TAC WEST
          flex: FLEX TURNOUT
          dream_low: DREAM LOW
          dream4: DREAM FOUR
          mmm4: MORMON MESA FOUR
        recoveries:
          stryk: STRYK
          acton: ACTON
          alamo: ALAMO
          arcoe: ARCOE
          bighorn: BIGHORN
          jaysn: JAYSN
          mintt: MINTT
          mopar: MOPAR
          rammm: RAMMM
          timbr: TIMBR
          flush: FLUSH
          hilz21l: HI-ILS or LOC/DME Z RWY 21L
          ht3r: HI-TACAN RWY 3R
          hty21l: HI-TACAN Y RWY 21L
          htz21l: HI-TACAN Z RWY 21L
          ilx21l: ILS or LOC/DME X RWY 21L
          iz21l: ILS or LOC/DME Z RWY 21L
          ly21L: LOC Y RWY 21L
          t21l: TACAN RWY 21L
          tx21l: TACAN X RWY 21L
      creech:
        name: Creech AFB
        tacan: 87X
        atis: 122.5
        tower: 360.7
        ground: 275.8
        recoveries:
          ht8: HI-TACAN RWY 8
          ht26: HI-TACAN RWY 26
    support:
      overlord:
        callsign: MAGIC
        type: AWACS (E-3A)
        comms: 377.8
        speed: 500
      fac_hill:
        callsign: HILL
        type: FAC
        position: N3639.81 W11546.88
      ar624:
        callsign: TEXACO 2
        type: TANKER (KC-135)
        comms: 289.7
        tacan: 95Y
        position: "AR-624: CDC 166/102 (N3605 W11305)"
        altitude: FL220
        speed: 420
      ar625:
        callsign: ARCO 1
        type: TANKER (KC-135MPRS)
        comms: 319.8
        tacan: 113Y
        position: "AR-625: MVA 168/77 (N3717 W11802)"
        altitude: FL250
        speed: 450
      ar635:
        callsign: SHELL 2
        type: TANKER (KC-135MPRS)
        comms: 360.8
        tacan: 115Y
        position: "AR-635: MLF 260/127 (N3831 W11542)"
        altitude: FL250
        speed: 430
      ar641:
        callsign: TEXACO 1
        type: TANKER (KC-135)
        comms: 265.0
        tacan: 94Y
        position: "AR-641A: CDC 242/78 (N3728 W11439)"
        altitude: 17000
        speed: 290
      ar231:
        callsign: TEXACO 3
        type: TANKER (KC-130)
        comms: 300.05
        tacan: 31Y
        position: "AR-231V: BTY 126/37 (N3620 W11614)"
        altitude: 8000
        speed: 320
    waypoints:
      - name: ACTON
        dme: LSV 021/36
        pos: N3644.52 W11436.45
      - name: APEX
        dme: LSV 027/09
        pos: N3621.58 W11454.34
      - name: ARCOE
        dme: LSV 357/30
        pos: N3644.26 W11455.02
      - name: Alamo N Point
        dme: LSV 333/60
        pos: N3712.8 W11520.5
      - name: Alamo S Point
        dme: LSV 325/38
        pos: N3650.0 W11520.2
      - name: BIGHORN
        dme: LSV 347/97
        pos: N3752.00 W11502.00
      - name: Beatty
        pos: N3648.54 W11644.86
      - name: Belted Peak
        dme: TQQ 100/36
        pos: N3734.0 W11604.5
      - name: Bishop
        pos: N3722.62 W11821.99
      - name: Black Mt
        dme: TQQ 156/31
        pos: N3717.0 W11638.5
      - name: Boulder
        pos: N3559:75 W11451.82
      - name: CARPP
        dme: LSV 355/63
        pos: N3717.00 W11450.72
      - name: CESAR
        dme: LSV 290/85
        pos: N3700.49 W11630.51
      - name: CRAIG
        dme: LSV 263/5.5
        pos: N3615.25 W11508.27
      - name: Caliente A Ctr Point
        dme: ILC 207/47
        pos: N3739.0 W11500.0
      - name: Caliente B Ctr Point
        dme: ILC 192/38
        pos: N3740.0 W11443.0
      - name: Cedar City
        pos: N3747.24 W11304.90
      - name: Cedar Peak
        dme: TQQ 092/56
        pos: N3742.0 W11620.0
      - name: Coale Dale
        pos: N3800.20 W11746.23
      - name: Coyote Peak
        dme: TQQ 088/56
        pos: N3737.5 W11538.0
      - name: Creech AFB
        pos: N3635.20 W11540.12
      - name: DREAM
        dme: LAS 354/66 BLD 342/71
        pos: N3710.34 W11459.53
      - name: DUCK
        dme: LSV 052/7.5
        pos: N3617.84 W11453.09
      - name: Daggett
        pos: N3457.75 W11634.69
      - name: Dry Lake
        dme: LSV 017/15
        pos: N3627.68 W11452.21
      - name: ELKXX
        dme: LSV 001/100
        pos: N375200 W11430.00
      - name: Elgin N Point
        dme: LSV 007/70
        pos: N3721.0 W11432.0
      - name: Elgin S Point
        dme: LSV 012/42
        pos: N3653.0 W11440.0
      - name: FLEX
        dme: LSV 337/5
        pos: N3618.62 W11502.36
      - name: FLUSH
        dme: LSV 287/73
        pos: N3650.80 W11620.27
      - name: FYTTR
        dme: LSV 269/33
        pos: N3621.44 W11541.47
      - name: GARTH
        dme: LSV 302/90
        pos: N3717.96 W11621.26
      - name: GASS PEAK
        dme: LSV 309/12
        pos: N3624.14 W11510.66
      - name: Goffs
        pos: N3507.87 W11510.59
      - name: Groom Lake
        dme: INS 339/42
        pos: N3716.5 W11548.0
      - name: Groom Lake
        pos: N3713.91 W11548.16
      - name: Hector
        pos: N3447.83 W11627.78
      - name: JUNNO
        dme: BLD 346/44
        pos: N3643.80 W11452.77
      - name: Jettison Hill
        dme: LSV 350/5.2
        pos: N3619.88 W11501.17
      - name: Leach Lake
        dme: DAG 341/40
        pos: N3537.51 W11640.67
      - name: MINTT
        dme: LSV 339/28 LAS 351/38
        pos: N3642.74 W11506.29
      - name: MOOSE
        dme: LSV 016/94
        pos: N3736.77 W11404.42
      - name: MOPAR
        dme: BTY 347/29
        pos: N3717.00 W11645.00
      - name: McCarran Intl
        pos: N3604.78 W11509.59
      - name: Milford
        pos: N3821.62 W11300.79
      - name: Mina
        pos: N3833.92 W11801.97
      - name: Mormon Mesa
        pos: N3646.16 W11416.65
      - name: Mt Helen
        dme: TQQ 162/17
        pos: N3730.0 W11644.5
      - name: Mt Irish
        dme: TQQ 085/67
        pos: N3738.5 W11524.0
      - name: NIXON
        dme: LSV 292/30
        pos: N3632.01 W11532.25
      - name: NUGGE
        dme: BLD 346/68
        pos: N3707.83 W11453.29
      - name: Needles
        pos: N3445.96 W11428.43
      - name: Nellis
        pos: N3614.68 W11501.50
      - name: PIUTE
        dme: INS 245/21
        pos: N3630.68 W11605.69
      - name: Peach Springs
        pos: N3537.48 W11332.67
      - name: Quartzite Mt
        dme: TQQ 113/27
        pos: N3731.0 W11619.5
      - name: R63 Tower
        dme: INS 067/8
        pos: N3637.0 W11530.2
      - name: R64 W Circle
        dme: INS 354/6
        pos: N3640.9 W11540.4
      - name: RAMMM
        dme: LSV 024/38
        pos: N3645.00 W11433.33
      - name: Reveille Peak
        dme: TQQ 070/31
        pos: N3751.5 W11608.0
      - name: SARAH
        dme: LSV 315/25
        pos: N3636.45 W11518.03
      - name: SHOWW
        dme: BTY 099/37
        pos: N3634.25 W11602.27
      - name: SIMNS
        dme: LSV 276/8
        pos: N3617.34 W11510.75
      - name: STRIP
        dme: INS 114/24
        pos: N3620.60 W11516.48
      - name: STRYK
        dme: LSV 282/26
        pos: N3625.62 W11530.70
      - name: Silverbow
        pos: N3748.00 W11647.00
      - name: St George
        pos: N3705.29 W11335.53
      - name: Stonewall Mt
        dme: TQQ 207/21
        pos: N3730.0 W11703.0
      - name: Stuckey's Peak
        dme: LSV 004/52
        pos: N3704.1 W11444.3
      - name: Stuckey’s Peak
        dme: LSV 003/51
        pos: N3704.10 W11444.30
      - name: Student Gap
        dme: LSV 349/82
        pos: N3737.0 W11500.0
      - name: T-Bird Lake
        dme: LSV 334/45
        pos: N3658.1 W11513.5
      - name: TIMBR
        dme: LSV 011/33
        pos: N3645.00 W11444.58
      - name: TROUTT
        dme: LSV 323/63
        pos: N3717.00 W11507.05
      - name: TUCKY
        dme: BTY 212/18
        pos: N3635.50 W11700.10
      - name: Texas Lake
        dme: LSV 350/64
        pos: N3719.00 W11457.50
      - name: Texas Lake
        dme: LSV 351/64
        pos: N3719.0 W11457.5
      - name: Tonopah Muni
        pos: N3801.84 W11702.01
      - name: VETTT
        dme: LSV 030/31
        pos: N3637.34 W11435.19
      - name: Wilson Creek
        pos: N3815.02 W11423.65
      - name: Winner LZ
        dme: LSV 356/6
        pos: N3620.33 W11500.25
caucasus:
  name: Caucasus
gulf:
  name: Persian Gulf
airframes:
  a10: A-10C
  f18: F/A-18C
  av8b: AV-8B N/A
  f16: F-16
callsigns:
  - Cougar
  - Edelweiss
  - Holiday
  - Lion
  - Monster
  - Panther
  - Raptor
  - T-Rex
  - Tiger
  - Vanguard
missions:
  - Training
  - CAS
  - CAP
  - SEAD
  - Strike
  - FAC(A)
  - SCAR
  - CSAR
pilots:
  - Butcher
  - Chatterbox
  - DC
  - DirtDiver
  - G-Rex
  - Ghost
  - Hawk
  - Herby
  - Hercules
  - Jabba
  - Jemi
  - Loki
  - MKay
  - Marsy
  - Mütze
  - Nerkub
  - Poet
  - Prinz
  - Retai
  - SNAFU
  - Sandman
  - Siddharta
  - SkyRat
  - Sparrowhawk
  - Stiletto
  - Striker
  - Tammi
  - Tank
  - Toolface
  - toto
  - Tronix
  - Warblade
